### ISSUE TITLE
Trouble when using this plugin

### ISSUE THREAD

**Issue by FelixYan101** [arnodelorme/roiconnect#21]
I've been having some trouble using this.
I resampled my data to 100Hz. But I got an Error that says
'The length of segments cannot be greater than the length of the input signal.'
If you have any idea about what happened please let me know.

**Comment by arnodelorme** [comment]
Can you share the full error (line number etc...)

**Comment by FelixYan101** [comment]
Thanks for your reply.

signal.internal.spectral.weelchparse>segment_info(line 275) error

Error info says
Error occurred in function segment_info() at line 275


Arnaud Delorme ***@***.***> 于2022年11月1日周二 02:36写道：

**Comment by arnodelorme** [comment]
The error message does not help unfortunately.
Would you mind sharing your data and instructions on how to reproduce the issue?

**Comment by fpellegrini** [comment]
Another user reported to have the same issue. Apparently, it only appears for epoch lengths smaller than 2 sec. 

This is what she wrote: "We are mainly interested in the connectivity in a specific time window after stimulus onset.
We now epoched the data from 0 ms to 750 ms after stimulus onset (so epoch length is 0,75 sec).
We have a sample rate of 250 Hz meaning we have 188 timepoints in this window of 0,75 sec.
However, I run into problems when I want to calculate the ROI activity (using pop_roi_activity) as I get the following error:
Error using signal.internal.spectral.welchparse>segment_info
The length of the segments cannot be greater than the length of the input signal.

I tried running the code again with different epoch lengths, and it turns out that the line of code only works when there are 500 or more time points per epoch (which corresponds in our data to epochs of 2 seconds).

Could you think of any way how we could calculate the connectivity for smaller epochs (or specific time windows) like we have?
It is not possible to increase the length of our input signal (as we are not interested in what happens before the stimulus),
and I guess I can also not change the length of the segments in this welchparse function?"

I saw that we have a note in pop_roi_activity that says "This function is optimized to process 2-sec data epochs". Would be nice to make it available for shorter epochs too. @arnodelorme, do you know at which point the shorter epochs lead to problems?

**Comment by Diedesss** [comment]
I ran into the same error message that FelixYan101 got (as mentioned by Dr. Pellegrini in the message above).
Prof. Delorme replied that  ROIconnect only works with continuous data.
So after epoching, I might try :
EEG = eeg_epoch2continuous(EEG);

The script seems to work when I add this step.
There is, however, a warning when I calculate the connectivity that there are not enough epochs to perform bootstrap.
Not sure if this is a problem or not.

**Comment by fpellegrini** [comment]
Yes, that seems as a good work-around. However, I think the discontinuities of the resulting continuous data may impact the connectivity estimation. So if possible, I would still like to make the function available for shorter epochs too. We'll discuss this internally and keep you in the loop. 

The bootstrapping warning can be ignored in case you are not doing bootstrapping for statistical testing.

**Comment by stefanhaufe** [comment]
I suggest to extend the function to allow epoch data as input. In this case, the original epochs should be used instead of the 2sec splits. The lengths of the provided epochs will then determine the resulting frequency resolution. E.g. for 750 ms epochs, the frequency resolution would be 1.33 Hz. But the user could be given the option to specify the desired frequency resolution. If it is higher, zero padding on the left and right could be applied (after hanning window application on the original epoch). If it is lower, the epochs could be cut (but that should trigger a warning).

**Comment by Diedesss** [comment]
When using epochs in the current script there is also a problem when calculating the leadfield matrix. 
I could only calculate the leadfield matrix with the GUI when the epoch contained the stimulus (ie. 0 ms).
So for example an epoch 0 to 750 ms after stimulus onset worked, but 100 to 850 ms after stimulus onset did not work.
This is also maybe something that should be adapted when extending the function to allow epoch data as input.

**Comment by FelixYan101** [comment]
Thanks for the update.

I think I run in to the same problem since our we have the data as 1.3s per
epoch.


fpellegrini ***@***.***>于2022年11月4日 周五18:35写道：

**Comment by FelixYan101** [comment]
Since our we interested in both resting data( which can be analyzed as
continued  data) and task data(which after stimulus we  epoched a 1.3s
epoch.)

Does it means for current state (before your team update ROIconnect, the
only way to do the analysis is not to epoch the data?

fpellegrini ***@***.***>于2022年11月4日 周五18:35写道：

> Another user reported to have the same issue. Apparently, it only appears
> for epoch lengths smaller than 2 sec.
>
This is what she wrote: "We are mainly interested in the connectivity in a

**Comment by FelixYan101** [comment]
I tried the same method, which works for the script( only activity and
haven’t try to run the connectivity). Does it effect the next step of
connectivity analysis.

And one of our undergraduate student who only knows how to use eeglab GUI,
she tried the same step on eeglab GUI. And got a ERROR says that the
ROIconnect only works for 2a epoch data, and the process stop.
Since she only works with resting data, is there’s any way to do the same
step on eeglab GUI.

fpellegrini ***@***.***>于2022年11月4日 周五18:35写道：

**Comment by Diedesss** [comment]
@stefanhaufe How long would it take to extend the funtion to allow epoch data? 
I am working with a deadline and I now have to decide if I wait for the script to work with epoch data as input or take another approach. Thank you!

**Comment by Hiyeri** [comment]
We extended the function to allow epoch data as input, you can now use the original epochs, i.e., the function is not limited to 2s splits anymore. [test_flex_epochlength.m](https://github.com/arnodelorme/roiconnect/blob/51f7477c677ad31568e47de4cbf40c291e16b010/test_pipes/test_flex_epochlength.m) is a test script that performs source reconstruction on data with an epoch length of 1s. 

The user cannot specify a desired frequency resolution yet, we are working on this.
